# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/karitha/Programming/Python/donem-projesi-muhammetozmen/ui/done.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Başarılı!")
        Form.resize(402, 310)
        Form.setStyleSheet("background-image: url('./ui/appicons/paper_wallpaper.png');")
        self.icon = QtWidgets.QLabel(Form)
        self.icon.setGeometry(QtCore.QRect(230, 10, 161, 181))
        self.icon.setStyleSheet("image: url('./ui/appicons/parwrite.png');")
        self.icon.setText("")
        self.icon.setObjectName("icon")
        self.baslik = QtWidgets.QLabel(Form)
        self.baslik.setGeometry(QtCore.QRect(10, 0, 211, 81))
        self.baslik.setMinimumSize(QtCore.QSize(211, 81))
        self.baslik.setMaximumSize(QtCore.QSize(211, 81))
        self.baslik.setStyleSheet("font: 700 20pt \"Morning Breeze\";")
        self.baslik.setObjectName("baslik")
        self.altbaslik = QtWidgets.QLabel(Form)
        self.altbaslik.setGeometry(QtCore.QRect(10, 70, 191, 51))
        self.altbaslik.setStyleSheet("font: italic 15pt \"Morning Breeze\";")
        self.altbaslik.setObjectName("altbaslik")
        self.duyuru = QtWidgets.QLabel(Form)
        self.duyuru.setGeometry(QtCore.QRect(10, 200, 401, 61))
        self.duyuru.setStyleSheet("font: 300 14pt \"Morning Breeze\";")
        self.duyuru.setObjectName("duyuru")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(300, 270, 101, 31))
        self.pushButton.setStyleSheet("font: 700 11pt \"Baby Doll\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.confirm_exit_clicked)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.baslik.setText(_translate("Form", "Parwriting Başarılı!"))
        self.altbaslik.setText(_translate("Form", "Program başarıyla çalıştı"))
        self.duyuru.setText(_translate("Form", "Önceden belirtiğin dizinlerde işlenmiş dosyayı bulabilirsiniz!"))
        self.pushButton.setText(_translate("Form", "Tamam!"))

    def confirm_exit_clicked(self):
        import sys
        sys.exit()
    
    

def exit_pop():
    import sys
    app = QtWidgets.QApplication(sys.argv)
    page_main = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(page_main)
    page_main.show()
    sys.exit(app.exec_())